spring.application.name=Facturacion

spring.datasource.url=jdbc:postgresql://207.58.175.220:5432/bootcamp
spring.datasource.username=keyjo
spring.datasource.password=keyjo2024
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate (opcional para desarrollo)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
