spring.application.name=Facturacion

spring.datasource.url=jdbc:postgresql://207.58.175.220:5432/bootcamp
spring.datasource.username=keyjo
spring.datasource.password=keyjo2024
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA/Hibernate (opcional para desarrollo)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# Ruta donde se servira la documentacion
springdoc.api-docs.path=/v3/api-docs
scalar.path=/scalar



